# Generated by Django 4.0 on 2022-07-01 18:40

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[trips.models.validate_rating]),
        ),
    ]
